### ISSUE TITLE
Protection Plugins allow placing of blocks but not the destruction of blocks.

### ISSUE THREAD

**Issue by OofbOye** [KettleFoundation/Kettle#37]
From my testing, you can place blocks while an area is protected (tested using Factions AND World-guard) no matter your permissions, but you cannot destroy blocks unless you have access to the claim/op permissions. Am I just screwing up or is this fixable?

**Comment by Plysm** [comment]
Upon testing with World Guard I have the same issue with no error or anything in console.

**Comment by OofbOye** [comment]
Good to know someone else has the issue, let's hope it's fixable soon!

**Comment by Timardo** [comment]
Block place events are not being fired, because they are not even implemented. In CraftBukkit, they are implemented in method ItemStack#onItemUse but since Forge replaces this method on server with its own hook in ForgeHook#onPlaceItemIntoWorld the event won't be called even if implemented at the original place. I am currently working on rewriting the Spigot patches in which this issue should be fixed. It will still need testing though.

**Comment by Birbyy** [comment]
@Timardo How is that going?

**Comment by Timardo** [comment]
I am currently busy with my job, which should be done by the end of this month. Then, aolko has some work, but I should be able to spend time on both.

**Comment by RubyBae** [comment]
hey it's coronavirus time, which means more staying at home, any progress?

**Comment by josephworks** [comment]
@RubyBae unfortunately, although that is true, there are no developers for Kettle at the moment.
