### ISSUE TITLE
Mods Not Being Deleted? | Underlying issue with patching.

### ISSUE THREAD

**Issue by PulseBeat02** [KettleFoundation/Kettle#60]
Hi, I was running my modpack on Kettle and I removed a couple of mods. For example, I removed the client mod "Phosphor", or else it will crash the server.  However, when I run the server again, the mod jar file, configs, and folder regenerate, even though the original mod jar file, configs, and folders were already deleted. Is this normal behavior? If anyone can help, they are welcome to reach out to me.

**Comment by Timardo** [comment]
Phosphor can be downloaded by Aether. This is normal behavior and Kettle has nothing to do with it. Although it's sad that it crashes with Phosphor it's expected since it patches bunch of stuff to enhance whole lighting system. None of coremods except AppleCore have been proofed to not screw things with Kettle yet.

**Comment by GMatrixGames** [comment]
Hopefully, this will be fixed soon, I'm trying to figure out the use of Mixins, so that we wont have this type of issue.
